### ISSUE TITLE
isBase64_encoded only handled if application_load_balancer is True

### ISSUE THREAD

**Issue by kivismik** [sloev/python-lambdarest#73]
Currently, the isBase64_encoded is handled and passed further only if the application_load_balancer is set to True.

By changing
```
# if body is None, remove the key
if response.get("body") == None:
    response.pop("body")

if application_load_balancer: 
```
to

```
# if body is None, remove the key
if response.get("body") == None:
    response.pop("body")

if self.isBase64_encoded:
    response["isBase64Encoded"] = self.isBase64_encoded

if application_load_balancer: 
```

in `__init__.py` it would work OK.

**Comment by sloev** [comment]
after looking at the code i guess nothing stands in the way for this. Would you @kivismik be able to supply a pr on this?

**Comment by kivismik** [comment]
Hi, I'll do it today

**Comment by sloev** [comment]
@kivismik are you gonna submit a pr for this? 😄

**Comment by sloev** [comment]
closing the issue since lack of feedback
