### ISSUE TITLE
Invalid JSON causes Lambda function to 500

### ISSUE THREAD

**Issue by gswalden** [sloev/python-lambdarest#80]
If a user sets up lambdarest as in many of the examples (i.e. they don't wrap the whole thing in a try/catch), requests that POST invalid JSON crash the function, and will receive 500 errors. I am willing to write a patch for this once we reach a consensus of what should happen. My suggestion would be to return a 400 error.
https://github.com/sloev/python-lambdarest/blob/master/lambdarest/__init__.py#L365-L372

I've written a test demonstrating the server error:
https://github.com/sloev/python-lambdarest/compare/master...gswalden:master

**Comment by sloev** [comment]
@gswalden its fixed in release v11.0.0 (breaking change since change of interface from 500 to 400 on bad json)
will release in a moment
