### ISSUE TITLE
Options for configuring CORS and preflight requests

### ISSUE THREAD

**Issue by sphaugh** [sloev/python-lambdarest#83]
Is CORS handling within the scope of this project?

I'd like to configure CORS when I call `create_lambda_handler`. Maybe it would be sufficient to add a `headers` kwarg for my use case?

@sloev

**Comment by sphaugh** [comment]
Turns out SAM already supports this on the API Gateway: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-corsconfiguration.html

**Comment by sphaugh** [comment]
It looks like SAM only generates the `OPTIONS` method handlers. It doesn't also inject `Access-Control-Allow-Origin` into the handler responses. :(

**Comment by sphaugh** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html#apigateway-responding-to-cors-preflight

> **Enabling CORS support for Lambda or HTTP proxy integrations**
> 
> For a Lambda proxy integration or HTTP proxy integration, you can still set up the required OPTIONS response headers in API Gateway. However, your backend is responsible for returning the Access-Control-Allow-Origin and Access-Control-Allow-Headers headers, because a proxy integration doesn't return an integration response. 

I think it would be good to have the option to do this in `create_lambda_handler`.

**Comment by sloev** [comment]
I agree. Cors is a great feature.
Try to see if you can write it with tests and then we can iterate on it
together. The codebase is small so you should be able to find yourself a
sweet spot.


fre. 6. aug. 2021 20.21 skrev Sean Haugh ***@***.***>:

**Comment by sloev** [comment]
hi @sphaugh 
**your contribution has been released in v12.0.0**  🎉  🚀  🚢 

... i made one change before doing so:
> CORS has been made a function instead of a class as i am a firm believer in not introducing classes where state is unnecessary, benefit is that CORS now returns an enriched lambda_handler
>  https://github.com/sloev/python-lambdarest/commit/67ca67a5d4a9d88552690326bd2c89352a491eca#diff-ad335d0f3a324b5d60568c8347280b3d03b93e3e1b17397c766e74a9bb7400afL89
