### ISSUE TITLE
[Feature Request] Add support for form submission

### ISSUE THREAD

**Issue by furrycatherder** [sloev/python-lambdarest#86]
@sloev I have a decorator for handling form submissions with Werkzeug: https://gist.github.com/sphaugh/101c980d632ea2a6ccbbe03ac8526697

Can we integrate this with lambdarest? I was thinking it could be an option similar to `load_json`. I had tried to write a PR for it but couldn't get the unit tests to pass. 😕 

(Note that API Gateway doesn't send the `Content-Length` header for some reason, which is why I used `len(body)` instead.)

**Comment by sphaugh** [comment]
I'd also like to see `werkzeug.datastructures.Headers` used elsewhere, since API Gateway has the annoying quirk of sending lowercased headers while SAM local sends them as-is.

**Comment by sloev** [comment]
@sphaugh hi, can you submit the pr no matter if it passes unittests or not so i have something more for the eyes :-)

**Comment by sloev** [comment]
no action by submitter, closing issue

**Comment by sloev** [comment]
# ⚠️ lambdarest is not maintained anymore, if anybody wanna take over, please contact me by email: johannes.valbjorn+lambdarest at the usual domain that rimes on email
