### ISSUE TITLE
[BUG] fix problem with werkzeug.routing

### ISSUE THREAD

**Issue by pa-kudinov** [sloev/python-lambdarest#91]
werkzeug.routing does not contain 'NotFound' any more which imported in lambdarest/__init__.py
So after updating dependencies the project is not built.
Current workaround is to force werkzeug version to 2.1.2

https://github.com/sloev/python-lambdarest/blob/master/lambdarest/__init__.py#L6

@sloev could you look at it?

--- 
Looking forward to hear from you!
Pavel Kudinov

**Comment by sloev** [comment]
# ⚠️ lambdarest is not maintained anymore, if anybody wanna take over, please contact me by email: johannes.valbjorn+lambdarest at the usual domain that rimes on email

**Comment by sloev** [comment]
@pa-kudinov should be fixed in 12.0.1, can you verify?
